CREATE TABLE Giveaways (
	id BIGINT UNIQUE NOT NULL AUTO_INCREMENT,
	message_id BIGINT UNSIGNED NOT NULL,
	start_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	end_time DATETIME NOT NULL,
	max_winners BIGINT NOT NULL,
	prize TEXT NOT NULL,
	completed BOOLEAN NOT NULL DEFAULT FALSE,
	PRIMARY KEY (id)
);

CREATE TABLE GiveawayWinners (
	id BIGINT UNIQUE NOT NULL AUTO_INCREMENT,
	giveaway_id BIGINT NOT NULL,
	user_id BIGINT UNSIGNED NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT FK__giveaways FOREIGN KEY (giveaway_id) REFERENCES Giveaways(id)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);
